name: Deploy Library Management System

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: |
          docker build -t library-management-system:${{ github.sha }} .
          docker tag library-management-system:${{ github.sha }} library-management-system:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hwrd04
          password: Bingxian@1066

      - name: Push Docker Image
        run: |
          docker push library-management-system:${{ github.sha }}
          docker push library-management-system:latest

      # Add deployment steps here based on your hosting platform
      # For example, if deploying to a cloud service or your own server
