name: Deploy Library Management System

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: |
          docker build -t hwrd04/library-management-system:${{ github.sha }} .
          docker tag hwrd04/library-management-system:${{ github.sha }} hwrd04/library-management-system:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push hwrd04/library-management-system:${{ github.sha }}
          docker push hwrd04/library-management-system:latest

      # Add deployment steps here based on your hosting platform
      # For example, if deploying to a cloud service or your own server
